name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    stage: build
    image: maciekbaron/sgdk:latest
    script:
      # Build the rom using SGDK
      - make -f $GENDEV/sgdk/mkfiles/makefile.gen clean all
    artifacts:
      paths:
        # Save the result of the build (in our case, out/rom.bin)
        - out/
    only:
      refs:
        - master
        - merge_requests    

      # - name: ROM for Artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #    path: ${{ github.workspace }}\out\rom.bin
      #    name: ROM-${{ github.run_number }}
